build.gradle
src/main/java/com/cdancy/bitbucket/rest/features/BranchApi.java

* As it is forbidden in Checkstyle config. To make build pass.

Avoiding star import

---

src/main/java/com/cdancy/bitbucket/rest/BitbucketClient.java
src/main/java/com/cdancy/bitbucket/rest/domain/branch/Branch.java
src/main/java/com/cdancy/bitbucket/rest/domain/branch/BranchModel.java
src/main/java/com/cdancy/bitbucket/rest/domain/comment/Comments.java
src/main/java/com/cdancy/bitbucket/rest/domain/project/Project.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/PagedChangeResponse.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/PagedCommitResponse.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/PullRequest.java
src/main/java/com/cdancy/bitbucket/rest/domain/repository/Repository.java
src/main/java/com/cdancy/bitbucket/rest/domain/tags/Tag.java
src/test/java/com/cdancy/bitbucket/rest/features/BitbucketClientLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/BitbucketClientMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java

And fixed various compiler warnings.
Addresses #23

Fixed Builder implementation.

---

src/main/java/com/cdancy/bitbucket/rest/domain/comment/Comments.java
src/main/java/com/cdancy/bitbucket/rest/domain/common/Links.java
src/main/java/com/cdancy/bitbucket/rest/domain/common/LinksHolder.java
src/main/java/com/cdancy/bitbucket/rest/domain/project/Project.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/Author.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/Change.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/Commit.java
src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/PullRequest.java
src/main/java/com/cdancy/bitbucket/rest/domain/repository/Repository.java
src/main/java/com/cdancy/bitbucket/rest/options/CreatePullRequest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommentsApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiMockTest.java

Same work as in PR #25, but for "Links" attributes this time.

Factorize Links attributes in domain classes with LinksHolder interface

---

src/test/java/com/cdancy/bitbucket/rest/BitbucketApiMetadataTest.java
src/test/java/com/cdancy/bitbucket/rest/features/BitbucketClientLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/BitbucketClientMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/BranchApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/BranchApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommentsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommitsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommitsApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/SystemApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/SystemApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/internal/BaseBitbucketMockTest.java

[Used script provided here](https://raw.githubusercontent.com/joel-costigliola/assertj-core/master/src/main/scripts/convert-junit-assertions-to-assertj-on-osx.sh) to convert testng assertions to assertj.

Convert testng assertions to assertj

---

gradle/wrapper/gradle-wrapper.properties

Upgrade to gradle 3.5

---

src/main/java/com/cdancy/bitbucket/rest/features/AdminApi.java
src/test/java/com/cdancy/bitbucket/rest/BaseBitbucketApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/AdminApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/AdminApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiLiveTest.java
src/test/resources/admin-list-users.json

@j0nathan33 FYI: also changed endpoint `AdminApi.listUserByGroup` to `AdminApi.listUsersByGroup`.

AdminApi gained endpoint 'listUsers'.

---

src/main/java/com/cdancy/bitbucket/rest/domain/file/Blame.java
src/main/java/com/cdancy/bitbucket/rest/domain/file/Line.java
src/main/java/com/cdancy/bitbucket/rest/domain/file/LinePage.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/FileApi.java
src/test/java/com/cdancy/bitbucket/rest/BaseBitbucketApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommentsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiMockTest.java
src/test/resources/line-page-with-blame.json
src/test/resources/line-page.json

REFACTOR: renamed endpoint FileApi.rawContent to FileApi.getContent

ADDED: FileApi gained endpoint 'listLines'.

---

src/main/java/com/cdancy/bitbucket/rest/features/CommitsApi.java
src/test/java/com/cdancy/bitbucket/rest/features/BuildStatusApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommitsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/CommitsApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiLiveTest.java

Refactor of PR-116 to be more in line with project standards.

Refactor of PR-116 

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle to 4.3.1

---

src/main/java/com/cdancy/bitbucket/rest/domain/tags/TagPage.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/TagApi.java
src/test/java/com/cdancy/bitbucket/rest/TestUtilities.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiMockTest.java
src/test/resources/tag-page.json

#132: TagApi gained `list` endpoint

---

src/main/java/com/cdancy/bitbucket/rest/features/TagApi.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiMockTest.java

ISSUE-134: added delete endpoint to the TagApi

---

src/main/java/com/cdancy/bitbucket/rest/features/BranchApi.java
src/test/java/com/cdancy/bitbucket/rest/features/BranchApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/BranchApiMockTest.java

BranchApi gained endpoint 'info'

---

src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiLiveTest.java

This allows the PullRequestApiLiveTest to pass without relying on external test setup.
As [discussed](https://github.com/cdancy/bitbucket-rest/issues/146#issuecomment-411485691) in #146 this fixes the problem related to the test user not having the right permissions.
CC @cdancy

Grant predefined test user the repo read permission in the PullRequestApiLiveTest

---

src/test/java/com/cdancy/bitbucket/rest/features/WebHookApiMockTest.java
src/test/resources/repository-webhook-errors.json
src/test/resources/repository-webhook-page.json
src/test/resources/repository-webhook.json

Mock-tests for WebHookApi #177

Implementation of  mock-tests for WebHookApi

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

I updated some dependencies and the gradle version. The projects now also works with Java 12.

udpate dependencies

---

src/main/java/com/cdancy/bitbucket/rest/domain/repository/MergeConfig.java

227: Add MergeConfigType "PROJECT"

---

src/main/java/com/cdancy/bitbucket/rest/domain/labels/Label.java
src/main/java/com/cdancy/bitbucket/rest/domain/labels/LabelsPage.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/LabelsApi.java
src/test/java/com/cdancy/bitbucket/rest/features/LabelsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/LabelsApiMockTest.java
src/test/resources/labels-get-byname.json

Support to labels endpoint - filter by labelname

---

build.gradle
src/main/java/com/cdancy/bitbucket/rest/domain/repository/Repository.java
src/main/java/com/cdancy/bitbucket/rest/domain/repository/WebHook.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/options/CreateRepository.java
src/test/java/com/cdancy/bitbucket/rest/TestUtilities.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/WebHookApiLiveTest.java

Pull Request adding new EventType to WebHook-Class
**On automtatic closing of ISSUES**
closes #298

[WEBHOOK-API] #298

---

build.gradle
gradle.properties
src/main/java/com/cdancy/bitbucket/rest/features/ProjectApi.java
src/main/java/com/cdancy/bitbucket/rest/features/RepositoryApi.java
src/main/java/com/cdancy/bitbucket/rest/handlers/BitbucketErrorHandler.java

Issue: https://github.com/cdancy/bitbucket-rest/issues/280

ISSUE-280: fixing path for project and repository apis

---

src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java

This fixes #324 .
I guess the exception message has changed at some point and the mock test was not run so it was not caught.

Fix SyncApi test

---

build.gradle
src/main/java/com/cdancy/bitbucket/rest/domain/repository/MergeConfig.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiMockTest.java

Add commitSummaries field to MergeConfig model
