build.gradle
gradle.properties
src/main/java/com/cdancy/bitbucket/rest/domain/common/ErrorsWrapper.java
src/main/java/com/cdancy/bitbucket/rest/domain/common/Page.java
src/main/java/com/cdancy/bitbucket/rest/domain/common/Utils.java
src/main/java/com/cdancy/bitbucket/rest/domain/project/ProjectPage.java
src/main/java/com/cdancy/bitbucket/rest/domain/repository/RepositoryPage.java
src/main/java/com/cdancy/bitbucket/rest/features/ProjectApi.java
src/main/java/com/cdancy/bitbucket/rest/features/RepositoryApi.java
src/test/java/com/cdancy/bitbucket/rest/features/CommentsApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/internal/BaseBitbucketMockTest.java
src/test/resources/project-page-full.json
src/test/resources/project-page-truncated.json
src/test/resources/repository-page-full.json
src/test/resources/repository-page-truncated.json

Opening another PR. Seems I did a false maneuver integrating your comments...
Sorry for the lost remarks...

Paging api

---

src/main/java/com/cdancy/bitbucket/rest/domain/pullrequest/User.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/AdminApi.java
src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java
src/test/java/com/cdancy/bitbucket/rest/TestUtilities.java
src/test/java/com/cdancy/bitbucket/rest/features/AdminApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/AdminApiMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java
src/test/resources/admin-delete-user-error.json
src/test/resources/admin-delete-user.json

For issue #144.
It's adding three endpoints - PUT for PR participant (main goal of PR) and two endpoints for admin api (POST and DELETE user) which are needed for participant PUT integ tests.

CreateUser, DeleteUser and AddParticipant endpoints

---

src/main/java/com/cdancy/bitbucket/rest/features/TagApi.java
src/test/java/com/cdancy/bitbucket/rest/features/TagApiMockTest.java

This fixes issue #150 
The fix is not elegant, but the underlying implementation by Atlassian is not elegant either. The merit this fix has is that it keeps all the TagApi operations under the same class.
If you have a suggestion on how to do this better, let me know.
CC @cdancy

Fix the delete Tag REST api path

---

build.gradle
src/test/java/com/cdancy/bitbucket/rest/TestUtilities.java

This addresses the concern raised in PR #148 in this [comment](https://github.com/cdancy/bitbucket-rest/pull/148#issuecomment-412190688).
The temporary git repositories created for the live test are now deleted when they are no longer needed.

Remove the git test directories when live tests are done

---

src/main/java/com/cdancy/bitbucket/rest/domain/project/ProjectPermissions.java
src/main/java/com/cdancy/bitbucket/rest/domain/project/ProjectPermissionsPage.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/ProjectApi.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiMockTest.java
src/test/resources/project-permission-group-error.json
src/test/resources/project-permission-group.json
src/test/resources/project-permission-users-error.json
src/test/resources/project-permission-users.json

Adding project level permissions API (#159) which is very similar to repository level permissions (most of the code reused and tests added too).

Adding project permissions #159

---

src/main/java/com/cdancy/bitbucket/rest/domain/comment/TaskAnchor.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java
src/test/resources/pull-request-activities.json

The presence of a like was unexpected and would lead to a parsing failure:
```
ERROR [2019-01-15 00:21:03,721] org.jclouds.http.functions.ParseJson: Error parsing input: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 141 column 29 path $.values[4].comment.tasks[0].anchor.properties.
! java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 141 column 29 path $.values[4].comment.tasks[0].anchor.properties.
! at com.google.gson.stream.JsonReader.nextString(JsonReader.java:838)
! at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
// rest of stack omitted
```
Using [this diff](https://github.com/cdancy/bitbucket-rest/pull/106/files) as inspiration I have come up with a fix that can be used as is or as a base …

If a task contains both a comment and a like then parsing would fail.

---

src/main/java/com/cdancy/bitbucket/rest/domain/file/LastModified.java
src/main/java/com/cdancy/bitbucket/rest/domain/file/LastModifiedSummary.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/FileApi.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiMockTest.java
src/test/resources/last-modified-summary.json

Note the API [documentation](https://docs.atlassian.com/bitbucket-server/rest/6.0.0/bitbucket-rest.html#idp231) reads as if the "at" query parameter is optional. It says it will use the default branch. However, when writing integration tests, I always got an `com.atlassian.bitbucket.validation.ArgumentValidationException` when I excluded it saying "Streaming modifications requires a starting commit." so I made it required.

Issue-179 Implement last-modified API

---

src/main/java/com/cdancy/bitbucket/rest/features/FileApi.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/FileApiMockTest.java

Implement list files at path

---

src/main/java/com/cdancy/bitbucket/rest/features/RepositoryApi.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiMockTest.java
src/test/resources/repository-page-empty.json
src/test/resources/repository-page-single.json

- Update base path for RepositoryApi
- Create a new endpoint in RepositoryApi to list all repositories regardless of project
closes #190

RepositoryApi: Listing all repos regardless of project ( copy of #191) 

---

src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java

The tests now work even if there is only one page of results.
closes #199

fix RepositoryApiLiveTest

---

README.md

**This PR is based on issue :** [MVN Repository files not found #201 ](https://github.com/cdancy/bitbucket-rest/issues/201)
The PR is adding to the steps of adding bitbucket-rest as a dependency to your maven project and providing 2 different ways to include bintray repo either in settings.xml or within your project pom.xml.

Maven bintray readme

---

src/main/java/com/cdancy/bitbucket/rest/domain/insights/InsightReportData.java
src/main/java/com/cdancy/bitbucket/rest/domain/insights/InsightReportDataLink.java
src/test/java/com/cdancy/bitbucket/rest/features/InsightsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/InsightsApiMockTest.java

Adding Code Insight ReportData of DataTypes other than TEXT should now work
closes #208 
During live testing I got a few `*** Please tell me who you are.` messages, and I don't know how to fix these.
So the live tests could be broken.

use correct data formats in InsightReportData value

---

src/main/java/com/cdancy/bitbucket/rest/BitbucketApi.java
src/main/java/com/cdancy/bitbucket/rest/domain/sshkey/AccessKeyPage.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/KeysApi.java
src/main/java/com/cdancy/bitbucket/rest/options/CreateAccessKey.java
src/main/java/com/cdancy/bitbucket/rest/options/CreateKey.java
src/test/java/com/cdancy/bitbucket/rest/features/InsightsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/KeysApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/KeysApiMockTest.java
src/test/resources/accesskeys-create-wrong-key.json
src/test/resources/accesskeys-get-for-project.json
src/test/resources/accesskeys-get-for-repository.json
src/test/resources/accesskeys-get-wrong-id.json
src/test/resources/accesskeys-list-by-project.json
src/test/resources/accesskeys-list-by-repository.json
src/test/resources/accesskeys-list-empty.json

Hi @cdancy ,
This is a draft PR to implement the keys API endpoint discussed in #238 .
I've tested the new API manually, but I'm not finished with the automated tests yet.
I'm opening this draft PR, hoping to ask for feedback if I'm going to the right direction with the implementation:
- Is it okay to use the already existing `AccessKey` model objects for this endpoint? Semantically the new usecase uses them similarly as they are used in the already existing endpoint, but here we need a few additional optional parameters.
- Is it okay to not cover only a part of the Keys API? For my usecase, I only need querying and deleting access keys, but not creating and updating them.
Thanks,
David

238: Implement keys endpoints to list access keys

---

src/main/java/com/cdancy/bitbucket/rest/features/FileApi.java
src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java
src/main/java/com/cdancy/bitbucket/rest/features/SyncApi.java

In the FileApi, there is the function listLines, which gives plenty of parameters.
One of the parameters based on the Bitbucket documentation is "at", in your project it's "commitHash".
Unfortunately this is very confusing, as it is not referencing to a specific commit hash, but to a branch e.g.
So calling the API with `?at=refs/heads/master` or `?at=refs/tags/%myTag%` will give a valid result.
Putting a commitHash instead would produce an error message:
````
{
"errors": [
{
"context": null,
"exceptionName": "com.atlassian.bitbucket.content.NoSuchPathException",
"message": "The path \"xxx\" does not exist at revision \"9aa913957f1...\""
}
]
}
````
To avoid misunderstanding, the parameter should be named like in Bitbucket documentation as there is at least some documentation there
The …

Changed parameter name of query parameter "at" to "branchOrTag"

---

src/main/java/com/cdancy/bitbucket/rest/BitbucketApi.java
src/main/java/com/cdancy/bitbucket/rest/domain/labels/Labels.java
src/main/java/com/cdancy/bitbucket/rest/domain/labels/LabelsPage.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/features/LabelsApi.java
src/test/java/com/cdancy/bitbucket/rest/features/LabelsApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/LabelsApiMockTest.java
src/test/resources/labels-list.json

PR for #182 
Adding support to `/rest/api/1.0/labels` API endpoint in https://docs.atlassian.com/bitbucket-server/rest/6.0.0/bitbucket-rest.html#idp86

Adding labels api support

---

src/test/java/com/cdancy/bitbucket/rest/TestUtilities.java

closes #253 
This change makes the username comparison in TestUtilities consistent with how the username is presented when getting it from authentication info (`auth.authValue()`). Using `user.slug()` means the username is all lower case causing integ tests to fail if the user had put in a username like `JoeSmith` because the comparison ends up being on `joesmith != JoeSmith`. 
By using `user.name()` we get back the same name (in terms of case) as it seems to be stored in the auth info `auth.authValue()`. Login does not appear to be case sensitive though - so an alternative approach is just to normalise all username strings to lowercase and compare that.

Use user.name() instead of user.slug() to avoid case issues

---

src/main/java/com/cdancy/bitbucket/rest/domain/commit/Commit.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/test/java/com/cdancy/bitbucket/rest/features/CommitsApiMockTest.java
src/test/resources/commit.json

Allows committer & commiterTimestamp information from a commit to be retrieved with the CommitApi.
Closes #260

260: Add committer & committerTimestamp to Commit object

---

gradle.properties
src/main/java/com/cdancy/bitbucket/rest/domain/repository/PullRequestSettings.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/main/java/com/cdancy/bitbucket/rest/options/CreatePullRequestSettings.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/RepositoryApiMockTest.java
src/test/resources/pull-request-settings.json

Adds `unapproveOnUpdate` to `PullRequestSettings` and `CreatePullRequestSettings` in order to support getting and setting that property on repositories' PR settings.
closes #262
Please do not create a Pull Request without first creating an ISSUE.
Any change needs to be discussed before proceeding.
Failure to do so may result in the rejection of the Pull Request.
Explain the **details** for making this change: What existing problem does the Pull Request solve? Why is this feature beneficial?
**On adding new feautes/endpoints**
No more than 1 endpoint should be coded within a Pull Request. 
This alone requires enough code to review and adding more than 1 WILL result in your Pull Request either being ignored or rejected outright.
**On adding Mock and Integ Tests**
At _least_ 2 mock tests and …

Pr settings unapprove on update

---

src/main/java/com/cdancy/bitbucket/rest/domain/commit/Commit.java
src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/test/java/com/cdancy/bitbucket/rest/features/CommitsApiMockTest.java
src/test/resources/commit.json

Allows properties information from a commit to be retrieved with the CommitApi.
Closes #283

ISSUE-283: Add properties to Commit object

---

build.gradle
gradle/release.gradle

Necessity is mother of the invention... jcenter bintray is down right now. I can't postpone this anymore :-)
Eliminate dependency on grgit as its author does not maintain it anymore and it will not be migrated to mavenCentral.
This PR also removes `gradleUpdateCenter()` as this project is not a gradle plugin.
From https://blog.gradle.org/jcenter-shutdown
> You should avoid using the Plugin Portal as a repository, except for Gradle plugin projects.

Remove grgit and jcenter dependency

---

src/main/java/com/cdancy/bitbucket/rest/features/ProjectApi.java
src/test/java/com/cdancy/bitbucket/rest/BaseBitbucketMockTest.java
src/test/java/com/cdancy/bitbucket/rest/features/ProjectApiMockTest.java

This fixes #280.
Three mock tests are currently broken. I identified one problem: a missing ` @Path` in the `ProjectApi`. In this PR:
* Missing `@Path` annotation in `ProjectApi.java`
* Typo in testng `testName`
* Add packet tracing for easier test debugging
There is ONE more bug in SyncApiMockTest that I am still working on #324

Fix mock tests

---

.travis.yml

As per the [shadow plugin README](https://github.com/johnrengelman/shadow), Java 17 is not supported and trying to run `publishToMavenLocal` does not work with Java 17, so downgrading travis to run with Java 11.

Downgrade Java 11 to support the shadow plugin

---

src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java
src/main/java/com/cdancy/bitbucket/rest/options/EditPullRequest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiLiveTest.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java

Adds an endpoint for editing pull-request details since this doesn't exist yet.

ISSUE-334: Add endpoint to edit pull-requests

---

src/main/java/com/cdancy/bitbucket/rest/fallbacks/BitbucketFallbacks.java
src/test/java/com/cdancy/bitbucket/rest/features/PullRequestApiMockTest.java
src/test/resources/pull-request-create-error.json

Resolves #447
I've successfully tested the commit based on the branch of #446. The mock tests are successful and it works in my application against a real-world Bitbucket instance.
This PR here is against the `master` branch, which currently doesn't build. I'll rebase after #446 has been merged.

Fix NPE in error response parsing
